### ISSUE TITLE
Docker reporting container image rather than name

### ISSUE THREAD

**Issue by YP28** [johanneswuerbach/newrelic-sysmond-service#11]
Hi Johannes,

First of all, thanks for this service. It seems to run good on my CoreOS testing cluster. I do however have a question, is there any way the reporting containers could report using the container name rather than the image name?

Right now, when I log into NR, and navigate to the Docker section, it shows me that I'm running Node 0.12.7, but it doesn't show me what the name of the container is. This, in my opinion, will lead to confusion when there are multiple services running Node 0.12.7 on that host.

I think this is built into the pre-built image by you? Could you give me some tips on where to find the docker reporting script and whether it's even possible to achieve my goal?

Yordi

**Comment by johanneswuerbach** [comment]
Hey, I'm just providing the NewRelic agent to the docker socket on the machine. https://github.com/johanneswuerbach/newrelic-sysmond-service/blob/master/newrelic-sysmond.service#L9

Everything else is handled by newrelic and not in my control. :-(

**Comment by YP28** [comment]
Thanks for your feedback. I'll check in with the NR Engineering team.
