### ISSUE TITLE
Cannot access cgroup for 3 containers

### ISSUE THREAD

**Issue by PatrickHeneise** [johanneswuerbach/newrelic-sysmond-service#12]
I'm getting this error in the `ps logs`:

    2015-09-01 12:33:53.614 (25) error: Cannot access cgroup for 3 containers

Any idea what's going on there?

**Comment by johanneswuerbach** [comment]
No :-(, I think you need to contact NewRelic support about that.

**Comment by PatrickHeneise** [comment]
Will do. Is the container running the latest libraries etc.?

**Comment by johanneswuerbach** [comment]
Yes, 2.1.0.124 https://docs.newrelic.com/docs/release-notes/server-release-notes/servers-linux-release-notes

**Comment by PatrickHeneise** [comment]
Thanks! I guess I'm the only one with these problems then. Will get in touch with NewRelic.

**Comment by wildsurfer** [comment]
I have the same problem. @PatrickHeneise did you get any help from NewRelic support?
